version: "3"
services:
  nameresolver:
    image: dvdarias/docker-hoster
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
  node1storage:
    hostname: node1.local
    depends_on: 
      - nameresolver
    image: ffg
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command:
        - /bin/bash
        - -c
        - |
          rm /root/.filefilego_data/keystore/node_identity.json
          ./filefilego account create_node_key admin
          ./filefilego --rpc_services="*" --search_engine --storage --storage_dir="/home/" --storage_token="admintoken" --storage_fees_byte="10000" --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/ --bootstrap_nodes="/dns/host.docker.internal/tcp/10209/p2p/16Uiu2HAmScD2pAgjQxQLpfgod2bfZyajmJR4J9rfJ11jJq7w66LX"
  node2storage:
    hostname: node2.local
    image: ffg
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command:
        - /bin/bash
        - -c
        - |
          rm /root/.filefilego_data/keystore/node_identity.json
          ./filefilego account create_node_key admin
          ./filefilego --rpc_services="*" --search_engine --storage --storage_dir="/home/" --storage_token="admintoken" --storage_fees_byte="10000" --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/ --bootstrap_nodes="/dns/host.docker.internal/tcp/10209/p2p/16Uiu2HAmScD2pAgjQxQLpfgod2bfZyajmJR4J9rfJ11jJq7w66LX"
    depends_on:
      - node1storage
      
  # verifier:
  #   hostname: verifier.local
  #   image: ffg
  #   extra_hosts:
  #       - "host.docker.internal:host-gateway"
  #   volumes:
  #       - $FFG_VERIFIER_PATH/1.json:/root/.filefilego_data/keystore/node_identity.json
  #   command:
  #       - /bin/bash
  #       - -c
  #       - |
  #         ./filefilego --rpc_services="*" --search_engine --storage --storage_dir="/home/" --storage_token="admintoken" --storage_fees_byte="10000" --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/" --verify --data_verification_fees="0x9" data_verification_transaction_fees="0x1"
  #   depends_on:
  #     - node2storage