version: "3"
services:
  nameresolver:
    image: dvdarias/docker-hoster
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
  validator:
    hostname: validator.local
    image: ffg
    environment:
        - FFG_VERIFIER_PASSPHRASE=${FFG_VERIFIER_PASSPHRASE}
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
        - $FFG_VERIFIER_KEYPATH:/root/.filefilego_data/keystore/node_identity.json
    command:
        - /bin/bash
        - -c
        - |
          ./filefilego --debug --validator --validator_keypath="/root/.filefilego_data/keystore/node_identity.json" --node_identity_passphrase=$FFG_VERIFIER_PASSPHRASE --rpc_services="*" --search_engine --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/"

  node1storage:
    hostname: node1storage.local
    depends_on: 
      - nameresolver
      - validator
    image: ffg
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command:
        - /bin/bash
        - -c
        - |
          rm /root/.filefilego_data/keystore/node_identity.json
          ./filefilego address create_node_key admin
          ./filefilego --debug --node_identity_passphrase=admin --rpc_services="*" --search_engine --storage --storage_dir="/home/" --storage_token="admintoken" --storage_fees_byte="10000" --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/" --bootstrap_nodes="/dns/validator.local/tcp/10209/p2p/16Uiu2HAmVXbhxA1tiA9PRZJWwSk5jdMfWXbfeGWaubVeT7MZu8ie"

  node2storage:
    hostname: node2storage.local
    depends_on: 
      - nameresolver
      - validator
    image: ffg
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command:
        - /bin/bash
        - -c
        - |
          rm /root/.filefilego_data/keystore/node_identity.json
          ./filefilego address create_node_key admin
          ./filefilego --debug --node_identity_passphrase=admin --rpc_services="*" --search_engine --storage --storage_dir="/home/" --storage_token="admintoken" --storage_fees_byte="10000" --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/" --bootstrap_nodes="/dns/validator.local/tcp/10209/p2p/16Uiu2HAmVXbhxA1tiA9PRZJWwSk5jdMfWXbfeGWaubVeT7MZu8ie"

  dataverifier1:
    hostname: dataverifier1.local
    image: ffg
    depends_on: 
      - nameresolver
      - validator
    environment:
        - FFG_VERIFIER_PASSPHRASE=${FFG_VERIFIER_PASSPHRASE}
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
        - $FFG_VERIFIER1_KEYPATH:/root/.filefilego_data/keystore/node_identity.json
    command:
        - /bin/bash
        - -c
        - |
          ./filefilego --debug --verify --node_identity_passphrase=$FFG_VERIFIER_PASSPHRASE --rpc_services="*" --search_engine --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/" --data_verification_fees="8" --data_verification_transaction_fees="0x1" --bootstrap_nodes="/dns/validator.local/tcp/10209/p2p/16Uiu2HAmVXbhxA1tiA9PRZJWwSk5jdMfWXbfeGWaubVeT7MZu8ie"

  dataverifier2:
    hostname: dataverifier2.local
    image: ffg
    depends_on: 
      - nameresolver
      - validator
    environment:
        - FFG_VERIFIER_PASSPHRASE=${FFG_VERIFIER_PASSPHRASE}
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
        - $FFG_VERIFIER2_KEYPATH:/root/.filefilego_data/keystore/node_identity.json
    command:
        - /bin/bash
        - -c
        - |
          ./filefilego --debug --verify --node_identity_passphrase=$FFG_VERIFIER_PASSPHRASE --rpc_services="*" --search_engine --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/" --data_verification_fees="9" --data_verification_transaction_fees="0x1" --bootstrap_nodes="/dns/validator.local/tcp/10209/p2p/16Uiu2HAmVXbhxA1tiA9PRZJWwSk5jdMfWXbfeGWaubVeT7MZu8ie"

  superlightnode:
    hostname: superlightnode.local
    depends_on: 
      - nameresolver
      - validator
    image: ffg
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command:
        - /bin/bash
        - -c
        - |
          rm /root/.filefilego_data/keystore/node_identity.json
          ./filefilego address create_node_key admin
          ./filefilego --debug --super_light_node --node_identity_passphrase=admin --rpc_services="data_transfer,transaction,address,filefilego" --addr=0.0.0.0 --http --http_addr=0.0.0.0 --data_downloads_path="/home/ffg/Downloads/" --bootstrap_nodes="/dns/validator.local/tcp/10209/p2p/16Uiu2HAmVXbhxA1tiA9PRZJWwSk5jdMfWXbfeGWaubVeT7MZu8ie"
