// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: node/protocols/messages/messages.proto

package messages

import (
	block "github.com/filefilego/filefilego/internal/block"
	transaction "github.com/filefilego/filefilego/internal/transaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GossipPayload represents a gossip payload.
type GossipPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*GossipPayload_Blocks
	//	*GossipPayload_Transaction
	//	*GossipPayload_Query
	Message isGossipPayload_Message `protobuf_oneof:"message"`
}

func (x *GossipPayload) Reset() {
	*x = GossipPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protocols_messages_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipPayload) ProtoMessage() {}

func (x *GossipPayload) ProtoReflect() protoreflect.Message {
	mi := &file_node_protocols_messages_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipPayload.ProtoReflect.Descriptor instead.
func (*GossipPayload) Descriptor() ([]byte, []int) {
	return file_node_protocols_messages_messages_proto_rawDescGZIP(), []int{0}
}

func (m *GossipPayload) GetMessage() isGossipPayload_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *GossipPayload) GetBlocks() *ProtoBlocks {
	if x, ok := x.GetMessage().(*GossipPayload_Blocks); ok {
		return x.Blocks
	}
	return nil
}

func (x *GossipPayload) GetTransaction() *transaction.ProtoTransaction {
	if x, ok := x.GetMessage().(*GossipPayload_Transaction); ok {
		return x.Transaction
	}
	return nil
}

func (x *GossipPayload) GetQuery() *DataQueryRequestProto {
	if x, ok := x.GetMessage().(*GossipPayload_Query); ok {
		return x.Query
	}
	return nil
}

type isGossipPayload_Message interface {
	isGossipPayload_Message()
}

type GossipPayload_Blocks struct {
	Blocks *ProtoBlocks `protobuf:"bytes,1,opt,name=blocks,proto3,oneof"`
}

type GossipPayload_Transaction struct {
	Transaction *transaction.ProtoTransaction `protobuf:"bytes,2,opt,name=transaction,proto3,oneof"`
}

type GossipPayload_Query struct {
	Query *DataQueryRequestProto `protobuf:"bytes,3,opt,name=query,proto3,oneof"`
}

func (*GossipPayload_Blocks) isGossipPayload_Message() {}

func (*GossipPayload_Transaction) isGossipPayload_Message() {}

func (*GossipPayload_Query) isGossipPayload_Message() {}

// ProtoBlocks is the proto representation of blocks envelope.
type ProtoBlocks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*block.ProtoBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *ProtoBlocks) Reset() {
	*x = ProtoBlocks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protocols_messages_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBlocks) ProtoMessage() {}

func (x *ProtoBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_node_protocols_messages_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBlocks.ProtoReflect.Descriptor instead.
func (*ProtoBlocks) Descriptor() ([]byte, []int) {
	return file_node_protocols_messages_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoBlocks) GetBlocks() []*block.ProtoBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// DataQueryRequestProto represents a data query message.
type DataQueryRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes        [][]byte `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	FromPeerAddr string   `protobuf:"bytes,2,opt,name=fromPeerAddr,proto3" json:"fromPeerAddr,omitempty"`
	Hash         []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Timestamp    int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *DataQueryRequestProto) Reset() {
	*x = DataQueryRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protocols_messages_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQueryRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQueryRequestProto) ProtoMessage() {}

func (x *DataQueryRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_node_protocols_messages_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQueryRequestProto.ProtoReflect.Descriptor instead.
func (*DataQueryRequestProto) Descriptor() ([]byte, []int) {
	return file_node_protocols_messages_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DataQueryRequestProto) GetNodes() [][]byte {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DataQueryRequestProto) GetFromPeerAddr() string {
	if x != nil {
		return x.FromPeerAddr
	}
	return ""
}

func (x *DataQueryRequestProto) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *DataQueryRequestProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DataQueryResponseProto represents a data query response.
type DataQueryResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromPeerAddr     string   `protobuf:"bytes,1,opt,name=fromPeerAddr,proto3" json:"fromPeerAddr,omitempty"`
	TotalFeesGB      string   `protobuf:"bytes,2,opt,name=totalFeesGB,proto3" json:"totalFeesGB,omitempty"`
	Hash             []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	PublicKey        []byte   `protobuf:"bytes,4,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Signature        []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Nodes            [][]byte `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	UnavailableNodes [][]byte `protobuf:"bytes,7,rep,name=unavailableNodes,proto3" json:"unavailableNodes,omitempty"`
	Timestamp        int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *DataQueryResponseProto) Reset() {
	*x = DataQueryResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protocols_messages_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQueryResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQueryResponseProto) ProtoMessage() {}

func (x *DataQueryResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_node_protocols_messages_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQueryResponseProto.ProtoReflect.Descriptor instead.
func (*DataQueryResponseProto) Descriptor() ([]byte, []int) {
	return file_node_protocols_messages_messages_proto_rawDescGZIP(), []int{3}
}

func (x *DataQueryResponseProto) GetFromPeerAddr() string {
	if x != nil {
		return x.FromPeerAddr
	}
	return ""
}

func (x *DataQueryResponseProto) GetTotalFeesGB() string {
	if x != nil {
		return x.TotalFeesGB
	}
	return ""
}

func (x *DataQueryResponseProto) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *DataQueryResponseProto) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DataQueryResponseProto) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *DataQueryResponseProto) GetNodes() [][]byte {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DataQueryResponseProto) GetUnavailableNodes() [][]byte {
	if x != nil {
		return x.UnavailableNodes
	}
	return nil
}

func (x *DataQueryResponseProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// BlockchainHeightResponse represents the height of a node's blockchain.
type BlockchainHeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *BlockchainHeightResponse) Reset() {
	*x = BlockchainHeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protocols_messages_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainHeightResponse) ProtoMessage() {}

func (x *BlockchainHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_protocols_messages_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainHeightResponse.ProtoReflect.Descriptor instead.
func (*BlockchainHeightResponse) Descriptor() ([]byte, []int) {
	return file_node_protocols_messages_messages_proto_rawDescGZIP(), []int{4}
}

func (x *BlockchainHeightResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// BlockDownloadRequest represents a block download request range.
type BlockDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *BlockDownloadRequest) Reset() {
	*x = BlockDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protocols_messages_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDownloadRequest) ProtoMessage() {}

func (x *BlockDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_protocols_messages_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDownloadRequest.ProtoReflect.Descriptor instead.
func (*BlockDownloadRequest) Descriptor() ([]byte, []int) {
	return file_node_protocols_messages_messages_proto_rawDescGZIP(), []int{5}
}

func (x *BlockDownloadRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *BlockDownloadRequest) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

// BlockDownloadResponse represents a block download response.
type BlockDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From       uint64              `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To         uint64              `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Error      bool                `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	NodeHeight uint64              `protobuf:"varint,4,opt,name=node_height,json=nodeHeight,proto3" json:"node_height,omitempty"`
	Blocks     []*block.ProtoBlock `protobuf:"bytes,5,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *BlockDownloadResponse) Reset() {
	*x = BlockDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protocols_messages_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDownloadResponse) ProtoMessage() {}

func (x *BlockDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_protocols_messages_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDownloadResponse.ProtoReflect.Descriptor instead.
func (*BlockDownloadResponse) Descriptor() ([]byte, []int) {
	return file_node_protocols_messages_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BlockDownloadResponse) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *BlockDownloadResponse) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *BlockDownloadResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *BlockDownloadResponse) GetNodeHeight() uint64 {
	if x != nil {
		return x.NodeHeight
	}
	return 0
}

func (x *BlockDownloadResponse) GetBlocks() []*block.ProtoBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_node_protocols_messages_messages_proto protoreflect.FileDescriptor

var file_node_protocols_messages_messages_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x1a, 0x1d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x11, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x0d, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x48, 0x00, 0x52,
	0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x41, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x38,
	0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x29, 0x0a,
	0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x15, 0x44, 0x61, 0x74,
	0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d,
	0x50, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x66, 0x72, 0x6f, 0x6d, 0x50, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x8e,
	0x02, 0x0a, 0x16, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f,
	0x6d, 0x50, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x50, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x65, 0x65, 0x73, 0x47, 0x42, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x65, 0x65, 0x73, 0x47, 0x42, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x75, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x10, 0x75, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x32, 0x0a, 0x18, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x22, 0x3a, 0x0a, 0x14, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x74, 0x6f, 0x22,
	0x9d, 0x01, 0x0a, 0x15, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42,
	0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x66, 0x69, 0x6c, 0x65, 0x67, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x66, 0x69, 0x6c,
	0x65, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6e, 0x6f, 0x64,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_protocols_messages_messages_proto_rawDescOnce sync.Once
	file_node_protocols_messages_messages_proto_rawDescData = file_node_protocols_messages_messages_proto_rawDesc
)

func file_node_protocols_messages_messages_proto_rawDescGZIP() []byte {
	file_node_protocols_messages_messages_proto_rawDescOnce.Do(func() {
		file_node_protocols_messages_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_protocols_messages_messages_proto_rawDescData)
	})
	return file_node_protocols_messages_messages_proto_rawDescData
}

var file_node_protocols_messages_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_node_protocols_messages_messages_proto_goTypes = []interface{}{
	(*GossipPayload)(nil),                // 0: messages.GossipPayload
	(*ProtoBlocks)(nil),                  // 1: messages.ProtoBlocks
	(*DataQueryRequestProto)(nil),        // 2: messages.DataQueryRequestProto
	(*DataQueryResponseProto)(nil),       // 3: messages.DataQueryResponseProto
	(*BlockchainHeightResponse)(nil),     // 4: messages.BlockchainHeightResponse
	(*BlockDownloadRequest)(nil),         // 5: messages.BlockDownloadRequest
	(*BlockDownloadResponse)(nil),        // 6: messages.BlockDownloadResponse
	(*transaction.ProtoTransaction)(nil), // 7: transaction.ProtoTransaction
	(*block.ProtoBlock)(nil),             // 8: block.ProtoBlock
}
var file_node_protocols_messages_messages_proto_depIdxs = []int32{
	1, // 0: messages.GossipPayload.blocks:type_name -> messages.ProtoBlocks
	7, // 1: messages.GossipPayload.transaction:type_name -> transaction.ProtoTransaction
	2, // 2: messages.GossipPayload.query:type_name -> messages.DataQueryRequestProto
	8, // 3: messages.ProtoBlocks.blocks:type_name -> block.ProtoBlock
	8, // 4: messages.BlockDownloadResponse.blocks:type_name -> block.ProtoBlock
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_node_protocols_messages_messages_proto_init() }
func file_node_protocols_messages_messages_proto_init() {
	if File_node_protocols_messages_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_protocols_messages_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_protocols_messages_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoBlocks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_protocols_messages_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQueryRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_protocols_messages_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQueryResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_protocols_messages_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainHeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_protocols_messages_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_protocols_messages_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_node_protocols_messages_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GossipPayload_Blocks)(nil),
		(*GossipPayload_Transaction)(nil),
		(*GossipPayload_Query)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_protocols_messages_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_protocols_messages_messages_proto_goTypes,
		DependencyIndexes: file_node_protocols_messages_messages_proto_depIdxs,
		MessageInfos:      file_node_protocols_messages_messages_proto_msgTypes,
	}.Build()
	File_node_protocols_messages_messages_proto = out.File
	file_node_protocols_messages_messages_proto_rawDesc = nil
	file_node_protocols_messages_messages_proto_goTypes = nil
	file_node_protocols_messages_messages_proto_depIdxs = nil
}
