// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: messages.proto

package node

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TransactionDataPayloadType int32

const (
	TransactionDataPayloadType_NONE                       TransactionDataPayloadType = 0
	TransactionDataPayloadType_UPDATE_BLOCKCHAIN_SETTINGS TransactionDataPayloadType = 1
	TransactionDataPayloadType_CREATE_NODE                TransactionDataPayloadType = 2
	TransactionDataPayloadType_UPDATE_NODE                TransactionDataPayloadType = 3
	TransactionDataPayloadType_DATA_CONTRACT              TransactionDataPayloadType = 4
)

// Enum value maps for TransactionDataPayloadType.
var (
	TransactionDataPayloadType_name = map[int32]string{
		0: "NONE",
		1: "UPDATE_BLOCKCHAIN_SETTINGS",
		2: "CREATE_NODE",
		3: "UPDATE_NODE",
		4: "DATA_CONTRACT",
	}
	TransactionDataPayloadType_value = map[string]int32{
		"NONE":                       0,
		"UPDATE_BLOCKCHAIN_SETTINGS": 1,
		"CREATE_NODE":                2,
		"UPDATE_NODE":                3,
		"DATA_CONTRACT":              4,
	}
)

func (x TransactionDataPayloadType) Enum() *TransactionDataPayloadType {
	p := new(TransactionDataPayloadType)
	*p = x
	return p
}

func (x TransactionDataPayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionDataPayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (TransactionDataPayloadType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x TransactionDataPayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionDataPayloadType.Descriptor instead.
func (TransactionDataPayloadType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type ChanNodeType int32

const (
	ChanNodeType_INVALIDNODE ChanNodeType = 0
	ChanNodeType_FILE        ChanNodeType = 1
	ChanNodeType_DIR         ChanNodeType = 2
	ChanNodeType_CHANNEL     ChanNodeType = 3
	ChanNodeType_SUBCHANNEL  ChanNodeType = 4
	ChanNodeType_ENTRY       ChanNodeType = 5
	ChanNodeType_OTHER       ChanNodeType = 6
)

// Enum value maps for ChanNodeType.
var (
	ChanNodeType_name = map[int32]string{
		0: "INVALIDNODE",
		1: "FILE",
		2: "DIR",
		3: "CHANNEL",
		4: "SUBCHANNEL",
		5: "ENTRY",
		6: "OTHER",
	}
	ChanNodeType_value = map[string]int32{
		"INVALIDNODE": 0,
		"FILE":        1,
		"DIR":         2,
		"CHANNEL":     3,
		"SUBCHANNEL":  4,
		"ENTRY":       5,
		"OTHER":       6,
	}
)

func (x ChanNodeType) Enum() *ChanNodeType {
	p := new(ChanNodeType)
	*p = x
	return p
}

func (x ChanNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChanNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (ChanNodeType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x ChanNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChanNodeType.Descriptor instead.
func (ChanNodeType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type GossipPayload_GossipPayloadType int32

const (
	GossipPayload_BLOCK              GossipPayload_GossipPayloadType = 0
	GossipPayload_TRANSACTION        GossipPayload_GossipPayloadType = 1
	GossipPayload_DATA_QUERY_REQUEST GossipPayload_GossipPayloadType = 2
)

// Enum value maps for GossipPayload_GossipPayloadType.
var (
	GossipPayload_GossipPayloadType_name = map[int32]string{
		0: "BLOCK",
		1: "TRANSACTION",
		2: "DATA_QUERY_REQUEST",
	}
	GossipPayload_GossipPayloadType_value = map[string]int32{
		"BLOCK":              0,
		"TRANSACTION":        1,
		"DATA_QUERY_REQUEST": 2,
	}
)

func (x GossipPayload_GossipPayloadType) Enum() *GossipPayload_GossipPayloadType {
	p := new(GossipPayload_GossipPayloadType)
	*p = x
	return p
}

func (x GossipPayload_GossipPayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GossipPayload_GossipPayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[2].Descriptor()
}

func (GossipPayload_GossipPayloadType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[2]
}

func (x GossipPayload_GossipPayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GossipPayload_GossipPayloadType.Descriptor instead.
func (GossipPayload_GossipPayloadType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14, 0}
}

type AddressState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance []byte `protobuf:"bytes,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Nounce  []byte `protobuf:"bytes,2,opt,name=Nounce,proto3" json:"Nounce,omitempty"`
}

func (x *AddressState) Reset() {
	*x = AddressState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressState) ProtoMessage() {}

func (x *AddressState) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressState.ProtoReflect.Descriptor instead.
func (*AddressState) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *AddressState) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *AddressState) GetNounce() []byte {
	if x != nil {
		return x.Nounce
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp     int64          `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Data          []byte         `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	PrevBlockHash []byte         `protobuf:"bytes,3,opt,name=PrevBlockHash,proto3" json:"PrevBlockHash,omitempty"`
	Hash          []byte         `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Signature     []byte         `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Transactions  []*Transaction `protobuf:"bytes,6,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetPrevBlockHash() []byte {
	if x != nil {
		return x.PrevBlockHash
	}
	return nil
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Block) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash            []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	PubKey          string `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Nounce          string `protobuf:"bytes,3,opt,name=Nounce,proto3" json:"Nounce,omitempty"`
	Data            []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	From            string `protobuf:"bytes,5,opt,name=From,proto3" json:"From,omitempty"`
	To              string `protobuf:"bytes,6,opt,name=To,proto3" json:"To,omitempty"`
	Value           string `protobuf:"bytes,7,opt,name=Value,proto3" json:"Value,omitempty"`
	TransactionFees string `protobuf:"bytes,8,opt,name=TransactionFees,proto3" json:"TransactionFees,omitempty"`
	Signature       []byte `protobuf:"bytes,9,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Chain           []byte `protobuf:"bytes,10,opt,name=Chain,proto3" json:"Chain,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Transaction) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

func (x *Transaction) GetNounce() string {
	if x != nil {
		return x.Nounce
	}
	return ""
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transaction) GetTransactionFees() string {
	if x != nil {
		return x.TransactionFees
	}
	return ""
}

func (x *Transaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetChain() []byte {
	if x != nil {
		return x.Chain
	}
	return nil
}

type TransactionDataPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    TransactionDataPayloadType `protobuf:"varint,1,opt,name=Type,proto3,enum=node.TransactionDataPayloadType" json:"Type,omitempty"`
	Payload []byte                     `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *TransactionDataPayload) Reset() {
	*x = TransactionDataPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionDataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDataPayload) ProtoMessage() {}

func (x *TransactionDataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionDataPayload.ProtoReflect.Descriptor instead.
func (*TransactionDataPayload) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionDataPayload) GetType() TransactionDataPayloadType {
	if x != nil {
		return x.Type
	}
	return TransactionDataPayloadType_NONE
}

func (x *TransactionDataPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ChanNodeEnvelop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*ChanNode `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
}

func (x *ChanNodeEnvelop) Reset() {
	*x = ChanNodeEnvelop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChanNodeEnvelop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChanNodeEnvelop) ProtoMessage() {}

func (x *ChanNodeEnvelop) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChanNodeEnvelop.ProtoReflect.Descriptor instead.
func (*ChanNodeEnvelop) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ChanNodeEnvelop) GetNodes() []*ChanNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ChanNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Hash         string       `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	MerkleRoot   []byte       `protobuf:"bytes,3,opt,name=MerkleRoot,proto3" json:"MerkleRoot,omitempty"`
	BinlayerHash string       `protobuf:"bytes,4,opt,name=BinlayerHash,proto3" json:"BinlayerHash,omitempty"`
	Size         string       `protobuf:"bytes,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Owner        string       `protobuf:"bytes,6,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Enabled      bool         `protobuf:"varint,7,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	NodeType     ChanNodeType `protobuf:"varint,8,opt,name=NodeType,proto3,enum=node.ChanNodeType" json:"NodeType,omitempty"`
	ParentHash   string       `protobuf:"bytes,9,opt,name=ParentHash,proto3" json:"ParentHash,omitempty"`
	Description  string       `protobuf:"bytes,10,opt,name=Description,proto3" json:"Description,omitempty"`
	ContentType  string       `protobuf:"bytes,11,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Attributes   []string     `protobuf:"bytes,12,rep,name=Attributes,proto3" json:"Attributes,omitempty"`
	Admins       []string     `protobuf:"bytes,13,rep,name=Admins,proto3" json:"Admins,omitempty"`
	Posters      []string     `protobuf:"bytes,14,rep,name=Posters,proto3" json:"Posters,omitempty"`
	Timestamp    int64        `protobuf:"varint,15,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *ChanNode) Reset() {
	*x = ChanNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChanNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChanNode) ProtoMessage() {}

func (x *ChanNode) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChanNode.ProtoReflect.Descriptor instead.
func (*ChanNode) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ChanNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChanNode) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChanNode) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *ChanNode) GetBinlayerHash() string {
	if x != nil {
		return x.BinlayerHash
	}
	return ""
}

func (x *ChanNode) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ChanNode) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ChanNode) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ChanNode) GetNodeType() ChanNodeType {
	if x != nil {
		return x.NodeType
	}
	return ChanNodeType_INVALIDNODE
}

func (x *ChanNode) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *ChanNode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChanNode) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ChanNode) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ChanNode) GetAdmins() []string {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *ChanNode) GetPosters() []string {
	if x != nil {
		return x.Posters
	}
	return nil
}

func (x *ChanNode) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BinlayerBinaryItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerkleRootHash []byte `protobuf:"bytes,1,opt,name=MerkleRootHash,proto3" json:"MerkleRootHash,omitempty"`
	BinaryHash     string `protobuf:"bytes,2,opt,name=BinaryHash,proto3" json:"BinaryHash,omitempty"`
	FilePath       string `protobuf:"bytes,3,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	Size           int64  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *BinlayerBinaryItem) Reset() {
	*x = BinlayerBinaryItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinlayerBinaryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinlayerBinaryItem) ProtoMessage() {}

func (x *BinlayerBinaryItem) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinlayerBinaryItem.ProtoReflect.Descriptor instead.
func (*BinlayerBinaryItem) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BinlayerBinaryItem) GetMerkleRootHash() []byte {
	if x != nil {
		return x.MerkleRootHash
	}
	return nil
}

func (x *BinlayerBinaryItem) GetBinaryHash() string {
	if x != nil {
		return x.BinaryHash
	}
	return ""
}

func (x *BinlayerBinaryItem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *BinlayerBinaryItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DataQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes        []string `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	FromPeerAddr string   `protobuf:"bytes,2,opt,name=FromPeerAddr,proto3" json:"FromPeerAddr,omitempty"`
	Hash         string   `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Timestamp    int64    `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *DataQueryRequest) Reset() {
	*x = DataQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQueryRequest) ProtoMessage() {}

func (x *DataQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQueryRequest.ProtoReflect.Descriptor instead.
func (*DataQueryRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DataQueryRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DataQueryRequest) GetFromPeerAddr() string {
	if x != nil {
		return x.FromPeerAddr
	}
	return ""
}

func (x *DataQueryRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DataQueryRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DataQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromPeerAddr      string   `protobuf:"bytes,1,opt,name=FromPeerAddr,proto3" json:"FromPeerAddr,omitempty"`
	TotalFeesRequired string   `protobuf:"bytes,2,opt,name=TotalFeesRequired,proto3" json:"TotalFeesRequired,omitempty"`
	Hash              string   `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	PubKey            []byte   `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Signature         []byte   `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Nodes             [][]byte `protobuf:"bytes,6,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	Timestamp         int64    `protobuf:"varint,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *DataQueryResponse) Reset() {
	*x = DataQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataQueryResponse) ProtoMessage() {}

func (x *DataQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataQueryResponse.ProtoReflect.Descriptor instead.
func (*DataQueryResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DataQueryResponse) GetFromPeerAddr() string {
	if x != nil {
		return x.FromPeerAddr
	}
	return ""
}

func (x *DataQueryResponse) GetTotalFeesRequired() string {
	if x != nil {
		return x.TotalFeesRequired
	}
	return ""
}

func (x *DataQueryResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DataQueryResponse) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *DataQueryResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *DataQueryResponse) GetNodes() [][]byte {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DataQueryResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DataContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostResponse        *DataQueryResponse `protobuf:"bytes,1,opt,name=HostResponse,proto3" json:"HostResponse,omitempty"`
	VerifierPubKey      []byte             `protobuf:"bytes,2,opt,name=VerifierPubKey,proto3" json:"VerifierPubKey,omitempty"`
	RequesterNodePubKey []byte             `protobuf:"bytes,3,opt,name=RequesterNodePubKey,proto3" json:"RequesterNodePubKey,omitempty"`
}

func (x *DataContract) Reset() {
	*x = DataContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataContract) ProtoMessage() {}

func (x *DataContract) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataContract.ProtoReflect.Descriptor instead.
func (*DataContract) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DataContract) GetHostResponse() *DataQueryResponse {
	if x != nil {
		return x.HostResponse
	}
	return nil
}

func (x *DataContract) GetVerifierPubKey() []byte {
	if x != nil {
		return x.VerifierPubKey
	}
	return nil
}

func (x *DataContract) GetRequesterNodePubKey() []byte {
	if x != nil {
		return x.RequesterNodePubKey
	}
	return nil
}

type DataContractsEnvelop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contracts []*DataContract `protobuf:"bytes,1,rep,name=Contracts,proto3" json:"Contracts,omitempty"`
}

func (x *DataContractsEnvelop) Reset() {
	*x = DataContractsEnvelop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataContractsEnvelop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataContractsEnvelop) ProtoMessage() {}

func (x *DataContractsEnvelop) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataContractsEnvelop.ProtoReflect.Descriptor instead.
func (*DataContractsEnvelop) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *DataContractsEnvelop) GetContracts() []*DataContract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

type DataVerifierRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction  *Transaction `protobuf:"bytes,1,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	ContractHash []byte       `protobuf:"bytes,2,opt,name=ContractHash,proto3" json:"ContractHash,omitempty"`
}

func (x *DataVerifierRequestPayload) Reset() {
	*x = DataVerifierRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataVerifierRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVerifierRequestPayload) ProtoMessage() {}

func (x *DataVerifierRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVerifierRequestPayload.ProtoReflect.Descriptor instead.
func (*DataVerifierRequestPayload) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *DataVerifierRequestPayload) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *DataVerifierRequestPayload) GetContractHash() []byte {
	if x != nil {
		return x.ContractHash
	}
	return nil
}

type NodeDataRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node         []byte `protobuf:"bytes,1,opt,name=Node,proto3" json:"Node,omitempty"`
	ContractHash []byte `protobuf:"bytes,2,opt,name=ContractHash,proto3" json:"ContractHash,omitempty"`
	From         uint64 `protobuf:"varint,3,opt,name=From,proto3" json:"From,omitempty"`
	To           uint64 `protobuf:"varint,4,opt,name=To,proto3" json:"To,omitempty"`
}

func (x *NodeDataRangeRequest) Reset() {
	*x = NodeDataRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDataRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDataRangeRequest) ProtoMessage() {}

func (x *NodeDataRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDataRangeRequest.ProtoReflect.Descriptor instead.
func (*NodeDataRangeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *NodeDataRangeRequest) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeDataRangeRequest) GetContractHash() []byte {
	if x != nil {
		return x.ContractHash
	}
	return nil
}

func (x *NodeDataRangeRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *NodeDataRangeRequest) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

type NodeToFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Hash []byte `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Size uint64 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *NodeToFileInfo) Reset() {
	*x = NodeToFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeToFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeToFileInfo) ProtoMessage() {}

func (x *NodeToFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeToFileInfo.ProtoReflect.Descriptor instead.
func (*NodeToFileInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *NodeToFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeToFileInfo) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *NodeToFileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GossipPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    GossipPayload_GossipPayloadType `protobuf:"varint,1,opt,name=Type,proto3,enum=node.GossipPayload_GossipPayloadType" json:"Type,omitempty"`
	Payload []byte                          `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *GossipPayload) Reset() {
	*x = GossipPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipPayload) ProtoMessage() {}

func (x *GossipPayload) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipPayload.ProtoReflect.Descriptor instead.
func (*GossipPayload) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *GossipPayload) GetType() GossipPayload_GossipPayloadType {
	if x != nil {
		return x.Type
	}
	return GossipPayload_BLOCK
}

func (x *GossipPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type NodeHeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeHeight uint64 `protobuf:"varint,1,opt,name=NodeHeight,proto3" json:"NodeHeight,omitempty"`
}

func (x *NodeHeightResponse) Reset() {
	*x = NodeHeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeightResponse) ProtoMessage() {}

func (x *NodeHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeightResponse.ProtoReflect.Descriptor instead.
func (*NodeHeightResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *NodeHeightResponse) GetNodeHeight() uint64 {
	if x != nil {
		return x.NodeHeight
	}
	return 0
}

type BlockQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNoFrom uint64 `protobuf:"varint,1,opt,name=BlockNoFrom,proto3" json:"BlockNoFrom,omitempty"`
	BlockNoTo   uint64 `protobuf:"varint,2,opt,name=BlockNoTo,proto3" json:"BlockNoTo,omitempty"`
}

func (x *BlockQueryRequest) Reset() {
	*x = BlockQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockQueryRequest) ProtoMessage() {}

func (x *BlockQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockQueryRequest.ProtoReflect.Descriptor instead.
func (*BlockQueryRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *BlockQueryRequest) GetBlockNoFrom() uint64 {
	if x != nil {
		return x.BlockNoFrom
	}
	return 0
}

func (x *BlockQueryRequest) GetBlockNoTo() uint64 {
	if x != nil {
		return x.BlockNoTo
	}
	return 0
}

type BlockQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From       uint64   `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To         uint64   `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	Payload    []*Block `protobuf:"bytes,3,rep,name=Payload,proto3" json:"Payload,omitempty"`
	Error      bool     `protobuf:"varint,4,opt,name=Error,proto3" json:"Error,omitempty"`
	NodeHeight uint64   `protobuf:"varint,5,opt,name=NodeHeight,proto3" json:"NodeHeight,omitempty"`
}

func (x *BlockQueryResponse) Reset() {
	*x = BlockQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockQueryResponse) ProtoMessage() {}

func (x *BlockQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockQueryResponse.ProtoReflect.Descriptor instead.
func (*BlockQueryResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *BlockQueryResponse) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *BlockQueryResponse) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *BlockQueryResponse) GetPayload() []*Block {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BlockQueryResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *BlockQueryResponse) GetNodeHeight() uint64 {
	if x != nil {
		return x.NodeHeight
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x4e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x50, 0x72, 0x65,
	0x76, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x35, 0x0a, 0x0c,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0xfd, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x4e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x46,
	0x72, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x65, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x22, 0x68, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x34, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x37, 0x0a,
	0x0f, 0x43, 0x68, 0x61, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x12, 0x24, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0xbe, 0x03, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x4d,
	0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x42,
	0x69, 0x6e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x42, 0x69, 0x6e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x42, 0x69, 0x6e, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x26,
	0x0a, 0x0e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f,
	0x6f, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x7e, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x65, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xe3, 0x01, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x46, 0x72, 0x6f, 0x6d, 0x50, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x2c, 0x0a, 0x11, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x65, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x46, 0x65, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xa5, 0x01, 0x0a,
	0x0c, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x3b, 0x0a,
	0x0c, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x50, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x22, 0x48, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x12, 0x30, 0x0a, 0x09,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x22, 0x75,
	0x0a, 0x1a, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x33, 0x0a, 0x0b,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x22, 0x72, 0x0a, 0x14, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x54, 0x6f, 0x22, 0x4c, 0x0a, 0x0e, 0x4e, 0x6f, 0x64,
	0x65, 0x54, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x0d, 0x47, 0x6f, 0x73, 0x73,
	0x69, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x39, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x47,
	0x6f, 0x73, 0x73, 0x69, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x47, 0x6f, 0x73,
	0x73, 0x69, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x47,
	0x0a, 0x11, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x22, 0x34, 0x0a, 0x12, 0x4e, 0x6f, 0x64, 0x65, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x53, 0x0a,
	0x11, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f, 0x46, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f, 0x54,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f,
	0x54, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x25, 0x0a,
	0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x6f,
	0x64, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x4e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2a, 0x7b, 0x0a, 0x1a, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x42, 0x4c, 0x4f,
	0x43, 0x4b, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x49, 0x4e, 0x47, 0x53,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x4f, 0x44,
	0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x4f,
	0x44, 0x45, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x43, 0x4f, 0x4e,
	0x54, 0x52, 0x41, 0x43, 0x54, 0x10, 0x04, 0x2a, 0x65, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x4e,
	0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x52, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43,
	0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x42, 0x43,
	0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x54, 0x52,
	0x59, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x06, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_messages_proto_goTypes = []interface{}{
	(TransactionDataPayloadType)(0),      // 0: node.TransactionDataPayloadType
	(ChanNodeType)(0),                    // 1: node.ChanNodeType
	(GossipPayload_GossipPayloadType)(0), // 2: node.GossipPayload.GossipPayloadType
	(*AddressState)(nil),                 // 3: node.AddressState
	(*Block)(nil),                        // 4: node.Block
	(*Transaction)(nil),                  // 5: node.Transaction
	(*TransactionDataPayload)(nil),       // 6: node.TransactionDataPayload
	(*ChanNodeEnvelop)(nil),              // 7: node.ChanNodeEnvelop
	(*ChanNode)(nil),                     // 8: node.ChanNode
	(*BinlayerBinaryItem)(nil),           // 9: node.BinlayerBinaryItem
	(*DataQueryRequest)(nil),             // 10: node.DataQueryRequest
	(*DataQueryResponse)(nil),            // 11: node.DataQueryResponse
	(*DataContract)(nil),                 // 12: node.DataContract
	(*DataContractsEnvelop)(nil),         // 13: node.DataContractsEnvelop
	(*DataVerifierRequestPayload)(nil),   // 14: node.DataVerifierRequestPayload
	(*NodeDataRangeRequest)(nil),         // 15: node.NodeDataRangeRequest
	(*NodeToFileInfo)(nil),               // 16: node.NodeToFileInfo
	(*GossipPayload)(nil),                // 17: node.GossipPayload
	(*NodeHeightResponse)(nil),           // 18: node.NodeHeightResponse
	(*BlockQueryRequest)(nil),            // 19: node.BlockQueryRequest
	(*BlockQueryResponse)(nil),           // 20: node.BlockQueryResponse
}
var file_messages_proto_depIdxs = []int32{
	5,  // 0: node.Block.Transactions:type_name -> node.Transaction
	0,  // 1: node.TransactionDataPayload.Type:type_name -> node.TransactionDataPayloadType
	8,  // 2: node.ChanNodeEnvelop.Nodes:type_name -> node.ChanNode
	1,  // 3: node.ChanNode.NodeType:type_name -> node.ChanNodeType
	11, // 4: node.DataContract.HostResponse:type_name -> node.DataQueryResponse
	12, // 5: node.DataContractsEnvelop.Contracts:type_name -> node.DataContract
	5,  // 6: node.DataVerifierRequestPayload.Transaction:type_name -> node.Transaction
	2,  // 7: node.GossipPayload.Type:type_name -> node.GossipPayload.GossipPayloadType
	4,  // 8: node.BlockQueryResponse.Payload:type_name -> node.Block
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionDataPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChanNodeEnvelop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChanNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinlayerBinaryItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataContractsEnvelop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataVerifierRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDataRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeToFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeHeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
